spring.application.name=S3andAWS

cloud.aws.credentials.access-Key= //add accesskey using aws S3
cloud.aws.credentials.secret-Key=  //add secret-Key using aws S3
cloud.aws.region.static=   //ADD like ap-south-1

aws.bucket.name= //add create bucket name
